# Generated by Django 4.0 on 2022-06-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0005_alter_productimage_image'),
        ('account', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'додаткові дані користувачів', 'verbose_name_plural': 'додаткові дані користувачів'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'список побажань', 'verbose_name_plural': 'список побажань'},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Користувач'),
        ),
    ]
