# Generated by Django 4.0 on 2022-04-10 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'категорію',
                'verbose_name_plural': 'категорії',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефону')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('status', models.CharField(choices=[('Actual', 'Актуальний'), ('Pre_order', 'Попереднє замовлення'), ('not_actual', 'Не актуальний')], max_length=100, verbose_name='В наявності')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_app.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукти',
                'ordering': ('status', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва підкатегорії')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main_app.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'підкатегорія',
                'verbose_name_plural': 'підкатегорії',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main_app.models.ProductImage.image_folder, verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'зображення продукту',
                'verbose_name_plural': 'зображення продуктів',
                'ordering': ('product',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_app.subcategory', verbose_name='Підкатегорія'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('status', models.CharField(choices=[('new', 'Новий заказ'), ('in_progress', 'В обробці'), ('is_ready', 'Заказ готовий'), ('completed', 'Заказ виконаний')], default='new', max_length=100, verbose_name='Статус замовлення')),
                ('buying_type', models.CharField(choices=[('self', 'Самовивіз'), ('delivery', 'Служба доставки')], default='self', max_length=100, verbose_name='Тип замовлення')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения замовлення')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='main_app.customer', verbose_name='Покупець')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Загальна ціна')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.customer', verbose_name='Власник')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_age', models.CharField(choices=[('1_year', '1 рік'), ('2_years', '2 роки'), ('3_years', '3 роки'), ('4_years', '4 роки')], max_length=100, verbose_name='Вік рослини')),
                ('product_container', models.CharField(choices=[('0,5_l', '0,5 л'), ('1_l', '1 л'), ('2_l', '2 л'), ('3_l', '3 л'), ('4_l', '4 л'), ('5_l', '5 л')], max_length=100, verbose_name='Розмір контейнеру')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Ціна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'ціну продукту',
                'verbose_name_plural': 'ціни продуктів',
                'ordering': ('price',),
                'unique_together': {('product', 'product_age', 'product_container')},
            },
        ),
    ]
