# Generated by Django 4.0 on 2022-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('_actual', 'Актуальний'), ('_pre_order', 'Попереднє замовлення'), ('not_actual', 'Не актуальний')], max_length=100, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product_age',
            field=models.CharField(choices=[('1_year', '1 рік'), ('2_year', '2 роки'), ('3_year', '3 роки'), ('4_year', '4 роки')], max_length=100, verbose_name='Вік рослини'),
        ),
    ]
