# Generated by Django 4.0 on 2022-04-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_product_status_alter_productprice_product_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=123, verbose_name='Опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product_age',
            field=models.CharField(choices=[('1_year', '1 рік'), ('2_years', '2 роки'), ('3_years', '3 роки'), ('4_years', '4 роки')], max_length=100, verbose_name='Вік рослини'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
