# Generated by Django 4.0 on 2022-05-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('status_product', 'name'), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукти'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='status_product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
