# Generated by Django 4.0 on 2022-05-18 17:24

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=main_app.models.ProductImage.image_folder, verbose_name='зображення'),
        ),
    ]
