# Generated by Django 4.0 on 2022-07-29 20:06

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=main_app.models.SubCategory, verbose_name='зображення'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
