# Generated by Django 4.0 on 2022-08-01 21:02

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_subcategory_image_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to=main_app.models.SubCategory, verbose_name='мобільне зображення'),
        ),
    ]
