# Generated by Django 4.0 on 2022-08-04 15:02

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_subcategory_image_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва баннеру')),
                ('image', models.ImageField(upload_to=main_app.models.BannerPromotion.image_folder, verbose_name='зображення')),
                ('image_mobile', models.ImageField(upload_to=main_app.models.BannerPromotion.image_folder, verbose_name='зображення для маленьких екранів')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image_mobile',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to=main_app.models.SubCategory, verbose_name='зображення'),
        ),
    ]
