# Generated by Django 4.0 on 2022-08-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_bannerpromotion_options_bannerpromotion_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerpromotion',
            options={'ordering': ('-date',), 'verbose_name': 'банер для головної сторінки', 'verbose_name_plural': 'банери для головної сторінки'},
        ),
        migrations.RenameField(
            model_name='bannerpromotion',
            old_name='data',
            new_name='date',
        ),
    ]
