# Generated by Django 4.0 on 2022-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_bannerpromotion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name_plural',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва підкатегорії в множині'),
        ),
    ]
