# Generated by Django 4.0 on 2022-08-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_subcategory_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name_plural',
            field=models.CharField(max_length=255, verbose_name='Назва підкатегорії в множині'),
        ),
    ]
