# Generated by Django 4.0 on 2022-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_subcategory_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpromotion',
            name='link',
            field=models.CharField(default=1, max_length=255, verbose_name='посилання для банеру'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerpromotion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='назва банеру'),
        ),
    ]
