# Generated by Django 4.0 on 2022-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_bannerpromotion_link_alter_bannerpromotion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='name_plural',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва підкатегорії в множині'),
        ),
    ]
