# Generated by Django 4.0 on 2022-08-12 17:05

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_subcategory_image_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=main_app.models.Category.image_folder, verbose_name='Зображення'),
        ),
    ]
