# Generated by Django 4.0 on 2022-08-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('status_product', 'name'), 'verbose_name': 'продукт', 'verbose_name_plural': 'продуктів'},
        ),
    ]
