# Generated by Django 4.0 on 2022-04-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0003_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. пошта')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Поштовий індекс')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('paid', models.BooleanField(default=False, verbose_name='Сплачено')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('delivery_type', models.CharField(choices=[('pick_up', 'Самовивіз'), ('delivery_nova_p', 'Новою поштою'), ('delivery_ukr_p', 'Укрпоштою')], default='pick_up', max_length=100, verbose_name='Тип доставки')),
                ('status', models.CharField(choices=[('new', 'Нове замовлення'), ('in_progress', 'В обробці'), ('completed', 'Замовлення виконано')], default='new', max_length=100, verbose_name='Статус замовлення')),
                ('payment_type', models.CharField(choices=[('cash', 'Накладеним платежем'), ('card', 'Оплата на карту')], default='card', max_length=100, verbose_name='Тип оплати')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'ordering': ('status', '-created'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main_app.product', verbose_name='Продукт')),
            ],
        ),
    ]
