# Generated by Django 4.0 on 2022-04-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_description_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('status', '-created'), 'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Предмети замовлення', 'verbose_name_plural': 'Предмети замовлення'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_age',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_age', to='main_app.productprice', verbose_name='Вік рослини'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_container',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_container', to='main_app.productprice', verbose_name='Розмір контейнеру'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефону'),
        ),
    ]
