# Generated by Django 4.0 on 2022-05-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_age',
            field=models.CharField(max_length=100, verbose_name='Вік рослини'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_container',
            field=models.CharField(max_length=100, verbose_name='Розмір контейнеру'),
        ),
    ]
