# Generated by Django 4.0 on 2022-05-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('status_order', '-created'), 'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Ціна'),
        ),
    ]
