# Generated by Django 4.0 on 2022-06-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('new', 'Нове замовлення'), ('in_progress', 'В обробці'), ('completed', 'Виконано'), ('canceled', 'Скасовано')], default='new', max_length=100, verbose_name='Статус замовлення'),
        ),
    ]
