# Generated by Django 4.0 on 2022-06-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_consignment_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
    ]
