# Generated by Django 4.0 on 2022-06-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Користувач'),
            preserve_default=False,
        ),
    ]
